version: '3' # version of docker-compose to use

services: # configuring each container
  cc-app:
    image: node:10.16
    command: 
      - bash 
      - ./spinup.sh
    working_dir: /usr/src/app
    volumes: 
      - "./:/usr/src/app"
    links:
      - cc-mongo:mongodb
    ports:
      - "25:25"
      - "587:587"
      - "80:80"
      - "465:465"
    depends_on:
      - cc-mongo
  cc-mongo: 
    image: mongo:3.6 # which image to pull, in this case latest
    ports:
      - "27017:27017"
    volumes: # data to map to the container
      - "cc-db-test-data:/data/db"

volumes:
  cc-db-test-data: