{ assembly_district: '30',
  electoral_district: '35',
  part: 'B',
  office: 'Male County Committee',
  office_holder: 'Andrew Freitas',
  address: '',
  data_source: '/usr/src/app/scripts/../import/appointed-queens-dems.csv' },
 { assembly_district: '31',
  electoral_district: '79',
  part: 'A',
  office: 'Female County Committee',
  office_holder: 'Valerie West',
  address: '',
  data_source: '/usr/src/app/scripts/../import/appointed-queens-dems.csv' }
{ assembly_district: '33',
  electoral_district: '74',
  part: 'A',
  office: 'Male County Committee',
  office_holder: 'Deverne Williams',
  address: '',
  data_source: '/usr/src/app/scripts/../import/appointed-queens-dems.csv' }
 { assembly_district: '33',
  electoral_district: '74',
  part: 'A',
  office: 'Female County Committee',
  office_holder: 'Helen Williams',
  address: '',
  data_source: '/usr/src/app/scripts/../import/appointed-queens-dems.csv' }
{ assembly_district: '36',
  electoral_district: '19',
  part: 'A',
  office: 'Male County Committee',
  office_holder: 'John Bione',
  address: '',
  data_source: '/usr/src/app/scripts/../import/appointed-queens-dems.csv' }
 { assembly_district: '36',
  electoral_district: '51',
  part: 'A',
  office: 'Male County Committee',
  office_holder: 'Dennis Fitzgerald',
  address: '',
  data_source: '/usr/src/app/scripts/../import/appointed-queens-dems.csv' }
 { assembly_district: '36',
  electoral_district: '51',
  part: 'A',
  office: 'Female County Committee',
  office_holder: 'Agnes Connolly',
  address: '',
  data_source: '/usr/src/app/scripts/../import/appointed-queens-dems.csv' }
 { assembly_district: '37',
  electoral_district: '69',
  part: 'B',
  office: 'Female County Committee',
  office_holder: 'Lillian Buksa',
  address: '',
  data_source: '/usr/src/app/scripts/../import/appointed-queens-dems.csv' }
